# Generated by Django 4.1.6 on 2023-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="heading",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
